# This file was generated by GoReleaser. DO NOT EDIT.
cask "fsvc" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "76eb741090975f7a392a89310b5c8b6e4aa7160e78cef60d913c70070d76d64a"
      url "https://github.com/j4y-w4lk3r/fsvc/releases/download/v#{version}/fsvc_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bf16d406a6076e864b77e47f202c760cbc2afa2eed6b75f24474b781cfbe1877"
      url "https://github.com/j4y-w4lk3r/fsvc/releases/download/v#{version}/fsvc_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "370df045804ae44e19f5e9c352cb7108b6b4bea4bf2932a972a76d8ee5d9bfcf"
      url "https://github.com/j4y-w4lk3r/fsvc/releases/download/v#{version}/fsvc_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "998f875d228f099fb998cae0652439562179b164d3ad5e8bad0d9cb408556f32"
      url "https://github.com/j4y-w4lk3r/fsvc/releases/download/v#{version}/fsvc_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "fsvc"
  desc "Financial-services CLI: Revolut Business today, ING tomorrow. mTLS + JWT + OAuth client-assertion in one binary."
  homepage "https://github.com/j4y-w4lk3r/fsvc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fsvc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fsvc"]
    end
  end

  # No zap stanza required

end
